function ddr3 = acceleration_endEffector(in1,in2)
%ACCELERATION_ENDEFFECTOR
%    DDR3 = ACCELERATION_ENDEFFECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 22:55:30

ddth1 = in1(10,:);
ddth2 = in1(11,:);
ddx = in1(9,:);
dth1 = in1(6,:);
dth2 = in1(7,:);
l_1 = in2(7,:);
l_2 = in2(8,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_1.*t2;
t6 = cos(t4);
t7 = l_1.*t3;
t8 = sin(t4);
t9 = l_2.*t6;
t10 = l_2.*t8;
t11 = dth2.*t9;
t12 = dth2.*t10;
t13 = t5+t9;
t14 = t7+t10;
ddr3 = [ddx-ddth2.*t10-ddth1.*t14-dth2.*(t11+dth1.*t9)-dth1.*(t11+dth1.*t13);ddth2.*t9+ddth1.*t13-dth2.*(t12+dth1.*t10)-dth1.*(t12+dth1.*t14)];
