function Corr_Joint_Sp = Corr_arm(in1,in2)
%CORR_ARM
%    CORR_JOINT_SP = CORR_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Nov-2020 23:55:48

dth1 = in1(6,:);
dth2 = in1(7,:);
l_1 = in2(7,:);
l_2 = in2(8,:);
m1 = in2(2,:);
m2 = in2(3,:);
m3 = in2(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(th1);
t3 = sin(th2);
t4 = th1+th2;
t5 = m3.*2.0;
t6 = l_1.*t2;
t7 = cos(t4);
t8 = m2+t5;
t9 = dth2.*l_2.*t7;
t10 = t9.*2.0;
Corr_Joint_Sp = [-dth2.*((m2.*(t9+dth1.*l_2.*t7))./2.0+(m3.*(t10+dth1.*l_2.*t7.*2.0))./2.0)-dth1.*((m3.*(t10+dth1.*(t6+l_2.*t7).*2.0))./2.0+(m2.*(t9+dth1.*(t6+(l_2.*t7)./2.0).*2.0))./2.0+(dth1.*m1.*t6)./2.0);dth2.*l_1.*l_2.*t3.*t8.*(dth1.*2.0+dth2).*(-1.0./2.0);(dth1.^2.*l_1.*l_2.*t3.*t8)./2.0;0.0];
