function Grav_Joint_Sp = Grav_arm(in1,in2)
%GRAV_ARM
%    GRAV_JOINT_SP = GRAV_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Oct-2020 16:09:10

g = in2(10,:);
l_2 = in2(7,:);
l_3 = in2(8,:);
l_4 = in2(9,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
th3 = in1(4,:);
t2 = cos(th1);
t3 = th1+th2;
t4 = l_2.*t2;
t5 = cos(t3);
t6 = t3+th3;
t7 = cos(t6);
t8 = l_3.*t5;
t9 = (l_4.*t7)./2.0;
Grav_Joint_Sp = [0.0;(g.*m2.*t4)./2.0+g.*m3.*(t4+t8./2.0)+g.*m4.*(t4+t8+t9);g.*m4.*(t8+t9)+(g.*m3.*t8)./2.0;g.*m4.*t9];
