function Grav_Joint_Sp = Grav_arm(in1,in2)
%GRAV_ARM
%    GRAV_JOINT_SP = GRAV_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    07-Nov-2020 20:30:51

g = in2(10,:);
l_1 = in2(7,:);
l_2 = in2(8,:);
m1 = in2(2,:);
m2 = in2(3,:);
m3 = in2(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(th1);
t3 = th1+th2;
t4 = l_1.*t2;
t5 = cos(t3);
Grav_Joint_Sp = [0.0;g.*m3.*(t4+l_2.*t5)+g.*m2.*(t4+(l_2.*t5)./2.0)+(g.*m1.*t4)./2.0;(g.*l_2.*t5.*(m2+m3.*2.0))./2.0;0.0];
