function J = jacobian_endEffector(in1,in2)
%JACOBIAN_ENDEFFECTOR
%    J = JACOBIAN_ENDEFFECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Nov-2020 23:55:48

l_1 = in2(7,:);
l_2 = in2(8,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = l_2.*t3;
t6 = l_2.*t4;
t7 = -t6;
J = reshape([1.0,0.0,t7-l_1.*sin(th1),t5+l_1.*cos(th1),t7,t5,0.0,0.0],[2,4]);
