function dJ = jacobian_dot_endEffector(in1,in2)
%JACOBIAN_DOT_ENDEFFECTOR
%    DJ = JACOBIAN_DOT_ENDEFFECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Nov-2020 19:31:42

dth1 = in1(6,:);
dth2 = in1(7,:);
l_1 = in2(7,:);
l_2 = in2(8,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = dth2.*l_2.*t3;
t6 = dth2.*l_2.*t4;
t7 = -t5;
t8 = -t6;
dJ = reshape([0.0,0.0,t7-dth1.*(l_2.*t3+l_1.*cos(th1)),t8-dth1.*(l_2.*t4+l_1.*sin(th1)),t7-dth1.*l_2.*t3,t8-dth1.*l_2.*t4,0.0,0.0],[2,4]);
