function J = jacobian_endEffector(in1,in2)
%JACOBIAN_ENDEFFECTOR
%    J = JACOBIAN_ENDEFFECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Nov-2020 23:12:32

l_2 = in2(7,:);
l_3 = in2(8,:);
l_4 = in2(9,:);
th1 = in1(2,:);
th2 = in1(3,:);
th3 = in1(4,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+th3;
t6 = cos(t5);
t7 = sin(t5);
t8 = l_3.*t3;
t9 = l_3.*t4;
t10 = l_4.*t6;
t11 = l_4.*t7;
t12 = -t9;
t13 = -t11;
J = reshape([1.0,0.0,t12+t13-l_2.*sin(th1),t8+t10+l_2.*cos(th1),t12+t13,t8+t10,t13,t10],[2,4]);
