function keypoints = keypoints_coffeeArm(in1,in2)
%KEYPOINTS_COFFEEARM
%    KEYPOINTS = KEYPOINTS_COFFEEARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Oct-2020 16:09:10

l_2 = in2(7,:);
l_3 = in2(8,:);
l_4 = in2(9,:);
th1 = in1(2,:);
th2 = in1(3,:);
th3 = in1(4,:);
x = in1(1,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_2.*t2;
t6 = cos(t4);
t7 = l_2.*t3;
t8 = sin(t4);
t9 = t4+th3;
t10 = l_3.*t6;
t11 = l_3.*t8;
keypoints = reshape([x,0.0,t5+x,t7,t5+t10+x,t7+t11,t5+t10+x+l_4.*cos(t9),t7+t11+l_4.*sin(t9)],[2,4]);
