function dr3 = velocity_endEffector(in1,in2)
%VELOCITY_ENDEFFECTOR
%    DR3 = VELOCITY_ENDEFFECTOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Nov-2020 19:31:42

dth1 = in1(6,:);
dth2 = in1(7,:);
dx = in1(5,:);
l_1 = in2(7,:);
l_2 = in2(8,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
dr3 = [dx-dth1.*(l_2.*t4+l_1.*sin(th1))-dth2.*l_2.*t4;dth1.*(l_2.*t3+l_1.*cos(th1))+dth2.*l_2.*t3];
